import math
frase = input('Digite algo: ')
print('O tipo primitivo desse valor é: ',type(frase))
print('Só tem espaços? ',frase.isspace())
print('É um número? ',frase.isnumeric())
print('É alfabético? ',frase.isalpha())
print('É alfanumérico? ',frase.isalnum())
print('Está em maiúsculas? ',frase.isupper())
print('Está em minuculas? ',frase.islower())
print('Está capitalizada? ',frase.istitle())
